name: Export and Deploy Godot Project

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.4.1
  GODOT_BUILD: stable

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Export Godot Project
        uses: firebelley/godot-export@29965918cc35b77c465839035775e0e12dc87029
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_BUILD }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_BUILD }}_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_BUILD }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_BUILD }}_export_templates.tpz
          relative_project_path: ./
          cache: true
          verbose: true
          use_preset_export_path: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: dist/Web/

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: export
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
